FROM node:20

# set working directory
WORKDIR /usr/src/app

# copy package files
COPY package*.json ./

# install dependencies
RUN npm install

# copy rest of admin backend
COPY . .

# expose port
EXPOSE 3000

# run admin server
CMD ["node", "admin-side/server.js"]

